import { Language, Translation, Category } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    title: "HK Household Chef",
    subtitle: "Plan tailored meals, save money, and reduce food waste.",
    languageName: "English",
    familySizeLabel: "Number of People",
    peopleUnit: "People",
    dishInputLabel: "What do you want to cook?",
    dishInputPlaceholder: "e.g., Sweet and Sour Pork...",
    submitButton: "Get Plan",
    loadingMessage: "Chef is thinking...",
    ingredientsTitle: "Ingredients",
    commonIngredientsTitle: "Pantry & Seasonings",
    marketLabel: "Wet Market",
    supermarketLabel: "Supermarket",
    forPeople: "for {0} people",
    shoppingTipsTitle: "Buying Tips",
    wastePreventionTitle: "Zero Waste",
    cookingStepsTitle: "Instructions",
    resetButton: "Back",
    updateButton: "Update",
    errorTitle: "Oops!",
    errorMessage: "Something went wrong.",
    navHome: "Home",
    navExplore: "Explore",
    navSaved: "Saved",
    exploreTitle: "Discover Dishes",
    savedTitle: "My Cookbook",
    noSavedMessage: "No saved recipes yet. Start cooking!",
    saveButton: "Save Recipe",
    savedButton: "Saved",
    deleteButton: "Delete",
    priceDisclaimer: "Note: Prices are estimates only and may vary by location and season.",
    shareButton: "Share",
    shareSuccess: "Link copied!",
  },
  'zh-HK': {
    title: "香港住家廚神",
    subtitle: "為您的家庭量身定制食譜，慳錢同時減少廚餘。",
    languageName: "繁體中文",
    familySizeLabel: "家庭人數",
    peopleUnit: "人",
    dishInputLabel: "您想煮甚麼？",
    dishInputPlaceholder: "例如：菠蘿咕嚕肉...",
    submitButton: "獲取清單",
    loadingMessage: "大廚正在思考...",
    ingredientsTitle: "食材",
    commonIngredientsTitle: "通用調料",
    marketLabel: "街市",
    supermarketLabel: "超市",
    forPeople: "{0}人份",
    shoppingTipsTitle: "格價貼士",
    wastePreventionTitle: "零浪費",
    cookingStepsTitle: "烹飪步驟",
    resetButton: "返回",
    updateButton: "更新",
    errorTitle: "哎呀！",
    errorMessage: "發生錯誤，請重試。",
    navHome: "主頁",
    navExplore: "探索",
    navSaved: "收藏",
    exploreTitle: "探索靈感",
    savedTitle: "我的食譜",
    noSavedMessage: "暫未有收藏食譜。",
    saveButton: "收藏食譜",
    savedButton: "已收藏",
    deleteButton: "刪除",
    priceDisclaimer: "註：價格僅供參考，實際價格視乎地區、季節及市況而定。",
    shareButton: "分享",
    shareSuccess: "連結已複製！",
  },
  'zh-CN': {
    title: "香港住家厨神",
    subtitle: "为您的家庭量身定制食谱，省钱同时减少厨余。",
    languageName: "简体中文",
    familySizeLabel: "家庭人数",
    peopleUnit: "人",
    dishInputLabel: "您想煮什么？",
    dishInputPlaceholder: "例如：菠萝咕噜肉...",
    submitButton: "获取清单",
    loadingMessage: "大厨正在思考...",
    ingredientsTitle: "食材",
    commonIngredientsTitle: "通用调料",
    marketLabel: "菜市场",
    supermarketLabel: "超市",
    forPeople: "{0}人份",
    shoppingTipsTitle: "格价贴士",
    wastePreventionTitle: "零浪费",
    cookingStepsTitle: "烹饪步骤",
    resetButton: "返回",
    updateButton: "更新",
    errorTitle: "哎呀！",
    errorMessage: "发生错误，请重试。",
    navHome: "主页",
    navExplore: "探索",
    navSaved: "收藏",
    exploreTitle: "探索灵感",
    savedTitle: "我的食谱",
    noSavedMessage: "暂未有收藏食谱。",
    saveButton: "收藏食谱",
    savedButton: "已收藏",
    deleteButton: "删除",
    priceDisclaimer: "注：价格仅供参考，实际价格视乎地区、季节及市况而定。",
    shareButton: "分享",
    shareSuccess: "链接已复制！",
  }
};

export const CATEGORIES: Category[] = [
  {
    id: 'cantonese',
    icon: '🥢',
    label: { en: 'Cantonese Classics', 'zh-HK': '經典粵菜', 'zh-CN': '经典粤菜' },
    suggestions: ['菠蘿咕嚕肉', '滑蛋蝦仁', '粟米斑塊', '西蘭花炒帶子']
  },
  {
    id: 'steam',
    icon: '🐟',
    label: { en: 'Steamed Dishes', 'zh-HK': '清蒸系列', 'zh-CN': '清蒸系列' },
    suggestions: ['清蒸石斑', '蒸水蛋', '梅菜蒸肉餅', '蒜蓉粉絲蒸扇貝']
  },
  {
    id: 'soup',
    icon: '🥣',
    label: { en: 'Soups', 'zh-HK': '老火湯/滾湯', 'zh-CN': '老火汤/滚汤' },
    suggestions: ['青紅蘿蔔豬骨湯', '蕃茄薯仔湯', '西洋菜陳腎湯']
  },
  {
    id: 'quick',
    icon: '⚡',
    label: { en: 'Quick & Easy', 'zh-HK': '快手家常', 'zh-CN': '快手家常' },
    suggestions: ['番茄炒蛋', '洋蔥豬扒', '肉碎蒸豆腐']
  },
  {
    id: 'veggie',
    icon: '🥬',
    label: { en: 'Vegetables', 'zh-HK': '蔬菜/素食', 'zh-CN': '蔬菜/素食' },
    suggestions: ['蒜蓉炒菜心', '魚香茄子煲 (走肉)', '羅漢齋']
  }
];